version: '3'
services:
  app:
    container_name: node_app
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    env_file: .env
    environment:
      - DB_CONNECT=$DB_CONNECT
    volumes:
      - './app:/node/app'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
